POKEDEX = [
    {
        "id": 1,
        "num": "001",
        "name": "Bulbasaur",
        "type": ["Grass", "Poison"],
        "height_m": 0.71,
        "weight_kg": 6.9,
        "multipliers": [1.58],
    },
    {
        "id": 4,
        "num": "004",
        "name": "Charmander",
        "type": ["Fire"],
        "height_m": 0.61,
        "weight_kg": 8.5,
        "multipliers": [1.65],
    },
    {
        "id": 6,
        "num": "006",
        "name": "Charizard",
        "type": ["Fire", "Flying"],
        "height_m": 1.70,
        "weight_kg": 90.5,
        "multipliers": [1.79],
    },
    {
        "id": 7,
        "num": "007",
        "name": "Squirtle",
        "type": ["Water"],
        "height_m": 0.51,
        "weight_kg": 9.0,
        "multipliers": [2.10],
    },
    {
        "id": 9,
        "num": "009",
        "name": "Blastoise",
        "type": ["Water"],
        "height_m": 1.60,
        "weight_kg": 85.5,
        "multipliers": [2.10],
    },
    {
        "id": 25,
        "num": "025",
        "name": "Pikachu",
        "type": ["Electric"],
        "height_m": 0.41,
        "weight_kg": 6.0,
        "multipliers": [2.34],
    },
    {
        "id": 63,
        "num": "063",
        "name": "Abra",
        "type": ["Psychic"],
        "height_m": 0.89,
        "weight_kg": 19.5,
        "multipliers": [1.36, 1.95],
    },
    {
        "id": 92,
        "num": "092",
        "name": "Gastly",
        "type": ["Ghost", "Poison"],
        "height_m": 1.30,
        "weight_kg": 0.1,
        "multipliers": [1.78],
    },
    {
        "id": 129,
        "num": "129",
        "name": "Magikarp",
        "type": ["Water"],
        "height_m": 0.89,
        "weight_kg": 10.0,
        "multipliers": [10.10, 11.80],
    },
    {
        "id": 150,
        "num": "150",
        "name": "Mewtwo",
        "type": ["Psychic"],
        "height_m": 2.01,
        "weight_kg": 122.0,
        "multipliers": [1.50],
    },
]